<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFAiWaw8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFAiWaw8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFAiWaw8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFAiWaw8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFAiWaw8\App_KernelDevDebugContainer([
    'container.build_hash' => 'FAiWaw8',
    'container.build_id' => '1959f9e6',
    'container.build_time' => 1624486582,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFAiWaw8');
