<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_get_question' => [[], ['_controller' => 'App\\Controller\\ApiPostController::questions'], [], [['text', '/api/getQuestions']], [], []],
    'api_post_question' => [[], ['_controller' => 'App\\Controller\\ApiPostController::insert'], [], [['text', '/api/postQuestion']], [], []],
    'api_update_question' => [[], ['_controller' => 'App\\Controller\\ApiPostController::update'], [], [['text', '/api/updateQuestion']], [], []],
    'api_historic_CSV' => [[], ['_controller' => 'App\\Controller\\ApiPostController::getCSV'], [], [['text', '/api/historicCSV']], [], []],
    'api_entity_CSV' => [[], ['_controller' => 'App\\Controller\\ApiPostController::getEntityCSV'], [], [['text', '/api/entityCSV']], [], []],
    'api_CSV_entity' => [['entity_name'], ['_controller' => 'App\\Controller\\ApiPostController::getCSVEntity'], [], [['variable', '/', '[^/]++', 'entity_name', true], ['text', '/api/entityCSV']], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], []],
];
